#!/bin/bash

#while [ 1 ]
#do
#kill -9 15722
#done
copy Org-sample-file.txt computer_0.txt
copy Org-sample-file.txt computer_1.txt
copy Org-sample-file.txt computer_2.txt
copy Org-sample-file.txt computer_3.txt
copy Org-sample-file.txt computer_4.txt
